name: bikeshare_streamlit
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - jupyter
  - ipykernel
  - folium
  - geopy
  - shapely
  - pyproj
  - geopandas
  - fiona
  - certifi
  - requests
  - urllib3
  - openssl
  - sqlite

  - pip:
      - streamlit==1.34.1
      - streamlit-folium==0.22.1
      - altair==5.3.0
      - pydeck==0.9.1
      - rich==13.7.1
      - pillow
      - pyarrow
      - watchdog
