name: bikeshare_streamlit
channels:
  - conda-forge
  - defaults

dependencies:
<<<<<<< HEAD
  - python=3.13
  - pip
  - numpy
  - pandas
  - scikit-learn
=======
  - python=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - jupyter
>>>>>>> 90c7cfdf05056f3f4584029126d8e892b384b9a4
  - ipykernel
  - folium
  - geopy
  - shapely
  - pyproj
  - geopandas
  - fiona
  - certifi
  - requests
  - urllib3
  - openssl
  - sqlite

  - pip:
      - streamlit==1.34.0
      - streamlit-folium==0.22.1
      - altair==5.3.0
      - pydeck==0.9.1
      - rich==13.7.1
      - pillow
      - pyarrow
      - watchdog
